name: CI

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

jobs:
  npm-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4.1.0
        with:
          run_install: true

      - name: Run build
        run: pnpm build
        
  npm-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4.1.0
        with:
          run_install: true

      - name: Run tests
        run: pnpm test

  done:
    name: Done
    runs-on: ubuntu-latest
    if: always()
    needs:
      - npm-build
      - npm-test
    steps:
      - run: exit 1
        if: ${{ always() && (contains(needs.*.result, 'failure') || contains(needs.*.result, 'skipped') || contains(needs.*.result, 'cancelled')) }}
